# Generated by Django 3.2.13 on 2022-05-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWordScrabble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChallengedBy', models.CharField(default=None, max_length=100)),
                ('WordToPlay', models.CharField(default=None, max_length=100)),
                ('MaxScorePossible', models.IntegerField(default=None)),
                ('PlayedBy', models.CharField(default=None, max_length=100)),
                ('ScoreGained', models.IntegerField(default=None)),
            ],
        ),
    ]
