# Generated by Django 3.2.13 on 2022-05-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWordScrabble', '0003_auto_20220529_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='MaxScorePossible',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='ScoreGained',
            field=models.IntegerField(blank=True),
        ),
    ]
