# Generated by Django 3.2.13 on 2022-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWordScrabble', '0004_auto_20220529_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='ChallengedBy',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='MaxScorePossible',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='PlayedBy',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='ScoreGained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='WordToPlay',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
