# Generated by Django 3.2.13 on 2022-05-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWordScrabble', '0006_auto_20220529_0151'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamedetails',
            table='GameDetails',
        ),
    ]
