# Generated by Django 3.2.13 on 2022-05-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWordScrabble', '0007_alter_gamedetails_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamedetails',
            table=None,
        ),
    ]
