# Generated by Django 3.2.13 on 2022-05-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWordScrabble', '0008_alter_gamedetails_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetails',
            name='MaxScorePossible',
        ),
    ]
